source 'https://rubygems.org'

gem 'rails', ENV.fetch('RAILS_VERSION', '~> 8.1.0'), require: false
gem 'tzinfo-data', platforms: [:windows]

platforms :ruby do
  if ENV['DB'] == 'mysql'
    gem 'mysql2'
  elsif ENV['DB'] == 'postgres'
    gem 'pg'
  else
    gem 'sqlite3', '>= 2.0'
  end
end

spree_opts = if ENV['SPREE_PATH']
               { path: ENV['SPREE_PATH'] }
             else
               { github: 'spree/spree', branch: 'main', glob: 'spree/**/*.gemspec' }
             end
gem 'spree', spree_opts
gem 'spree_admin', spree_opts
gem 'spree_page_builder', path: '../page_builder'

gem 'spree_multi_store', github: 'spree/spree-multi-store', branch: 'main'
gem 'spree_posts', github: 'spree/spree-posts', branch: 'main'
gem 'spree_dev_tools', '>= 0.6.0.rc1'

gem 'devise'
gem 'kaminari'
gem 'propshaft'

gemspec
