require 'bundler'
Bundler::GemHelper.install_tasks

require 'rspec/core/rake_task'
require 'spree/testing_support/extension_rake'

RSpec::Core::RakeTask.new

task :default do
  if Dir['spec/dummy'].empty?
    Rake::Task[:test_app].invoke
    Dir.chdir('../../')
  end
  Rake::Task[:spec].invoke
end

desc 'Generates a dummy app for testing'
task :test_app do
  ENV['LIB_NAME'] = 'spree/storefront'
  Rake::Task['extension:test_app'].execute(
    user_class: 'Spree::User',
    admin_user_class: 'Spree::AdminUser',
    authentication: 'devise',
    install_admin: true,
    install_storefront: true,
    css: true,
    javascript: true
  )
  system({ 'BUNDLE_GEMFILE' => File.expand_path('Gemfile', __dir__) }, 'bundle exec rails g spree_posts:install')
end
